import Head from "next/head";
import Image from "next/image";
import About from "../components/about";
import Experience from "../components/experience";
import Footer from "../components/footer";
import Header from "../components/header";
import Hero from "../components/hero";
import Project from "../components/project";
import Skills from "../components/skill";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-[#020d02] text-[#ffffff] h-screen snap-y snap-mandatory overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Hero */}
      <Header />
      <section id="hero" className="snap-center ">
        <Hero />
      </section>
      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>
      {/* Experience */}
      <section id="experience" className="snap-center">
        <Experience/>
      </section>

      {/* Skill */}
      <section id="Skills" className="snap-center">
        <Skills/>
      </section>
      {/* Projects */}
      <section id='Project' className="snap-center">
      <Project/>
      </section>
      {/* Contact */}

      {/* Footer */}
      <section >
        <Footer/>
        </section>
    </div>
  );
}
