import Head from "next/head";
import Image from "next/image";
import About from "../components/about";
import Header from "../components/header";
import Hero from "../components/hero";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-[#020d02] text-[#ffffff] h-screen snap-y snap-mandatory overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <section id="hero" className="snap-center ">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      {/* Experience */}
      {/* Skill */}
      {/* Projects */}
      {/* Contact */}
      {/* Footer */}
    </div>
  );
}
